[build]
publish = "/public"
command = "hugo -d public && `npm bin`/decktape public/basics/slides/index.html public/basics.pdf"

[context.production.environment]
  HUGO_VERSION = "0.72.0"
  GO_VERSION="1.12"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.72.0"
  GO_VERSION="1.12"
  

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"